/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class BorrarClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form BorrarClientes
     */
    public BorrarClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlDni = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlCiudad = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCiudad = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jbBuscar = new javax.swing.JButton();

        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(0, 102, 102));
        jlTitulo.setText("Borrar Clientes");

        jlDni.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        jlDni.setForeground(new java.awt.Color(0, 153, 153));
        jlDni.setText("DNI");

        jlTelefono.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        jlTelefono.setForeground(new java.awt.Color(0, 153, 153));
        jlTelefono.setText("Teléfono");

        jlApellido.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(0, 153, 153));
        jlApellido.setText("Apellido");

        jlNombre.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(0, 153, 153));
        jlNombre.setText("Nombre");

        jlCiudad.setFont(new java.awt.Font("Arial Unicode MS", 1, 11)); // NOI18N
        jlCiudad.setForeground(new java.awt.Color(0, 153, 153));
        jlCiudad.setText("Ciudad");

        jtTelefono.setEditable(false);

        jtApellido.setEditable(false);

        jtNombre.setEditable(false);

        jtCiudad.setEditable(false);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefono)
                    .addComponent(jlDni)
                    .addComponent(jlApellido)
                    .addComponent(jlNombre)
                    .addComponent(jlCiudad))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtDni)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtCiudad, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jbBuscar)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDni)
                    .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTelefono)
                    .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCiudad)
                    .addComponent(jtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbSalir)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
       long dni = 0;
        // TODO add your handling code here:
        //Directorio l1 = FormularioClientes.getDirectorio();
        Directorio c = new Directorio();
        //Set<String> tel = c.keySet();
        Cliente cli = new Cliente();
        dni = Integer.parseInt(jtDni.getText());
        if(c.borrarCliente(dni)==false){
        JOptionPane.showMessageDialog(this, "Cliente Borrado");}
        else {
            JOptionPane.showMessageDialog(this,"No se encontro cliente");
        }
        //Cliente cli = FormularioClientes.getDirectorio().borrarCliente(dni);
           /* dni = Integer.parseInt(jtDni.getText());
            //jtTelefono.setText();
            jtNombre.setText(cli.getNombre());
            jtApellido.setText(cli.getApellido());
            jtCiudad.setText(cli.getCiudad());
      if (FormularioClientes.getDirectorio().borrarCliente(dni)) {
          JOptionPane.showMessageDialog(this,"No se encontro cliente");
      }
      else {
          c.borrarCliente(dni);
          JOptionPane.showMessageDialog(this,"Cliente: "+dni+" borrado");
      }*/
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCiudad;
    private javax.swing.JLabel jlDni;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtCiudad;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables
}
